// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7aQ4ZTqP48awNDZ0cBz6IhI9d3qBglZk',
    appId: '1:354676243619:android:f236bf10c1d4f1da835316',
    messagingSenderId: '354676243619',
    projectId: 'thera-track-app',
    storageBucket: 'thera-track-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6AfaJ8z1SqINfMKXok6JhKrh34r-3pY',
    appId: '1:354676243619:ios:6dba053d52fe274f835316',
    messagingSenderId: '354676243619',
    projectId: 'thera-track-app',
    storageBucket: 'thera-track-app.firebasestorage.app',
    iosBundleId: 'com.example.theraTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6AfaJ8z1SqINfMKXok6JhKrh34r-3pY',
    appId: '1:354676243619:ios:6dba053d52fe274f835316',
    messagingSenderId: '354676243619',
    projectId: 'thera-track-app',
    storageBucket: 'thera-track-app.firebasestorage.app',
    iosBundleId: 'com.example.theraTrackApp',
  );
}
